### ISSUE TITLE
Task list: Project 6 - Power Laws & Universality

### ISSUE THREAD

**Issue by z357412526** [berkeley-stat222/mousestyles#126]
Here is our project workflow for rest of this week and the rrr week.

1. Write function for estimating parameter by MLE
 - [x]  Truncated power law distribution.
 - [x]  Truncated exponential distribution.
2. Measure the goodness of fit
 - [ ] Figure out how to implement K-S test on truncated distribution.
 - [ ]  Pearson Chi-sq is another potential fitness test.
3. K-means Clustering
 - [ ]  Write function for k-mean and test on existing data.
4. Form a short conclusion/ report about the conclusion
 - [ ]  Write tests.
 - [ ]   A short summary regarding to the existing data.

@berkeley-stat222/z357412526 @lunadadada @CenzhuoYao  @FengshiNiu  @hduongtrong @doutib

**Comment by z357412526** [comment]
@lunadadada @CenzhuoYao @FengshiNiu @hduongtrong @doutib 
-Guys!
If we accomplish something, please cross them out here. If there is a change of the plan, just feel to revise the original issue.

Great job so far. Thank you!

**Comment by jarrodmillman** [comment]
@z357412526 Should this issue be closed?

**Comment by CenzhuoYao** [comment]
@jarrodmillman We have finished all the problems listed there. It can be closed now. Thanks.

cc: @z357412526 @lunadadada @FengshiNiu @hduongtrong @doutib
