### ISSUE TITLE
Data Loader

### ISSUE THREAD

**Issue by peterasujan** [berkeley-stat222/mousestyles#16]
- [x] actually try all the loading, use *mousestyles/mousestyles/data/__init__.py*
- [ ] Consult HTM_begin_script: check [this](https://www.msri.org/people/members/chillar/files/BY), change codes to functions

**Comment by dylandaniels** [comment]
What's the deliverable on this exactly? Are we trying to write some functions to put these into nice Panda dataframes?

**Comment by dylandaniels** [comment]
Tasks:

- [ ] **Task 1** Write a function which converts interval data into ```pandas.DataFrame```s. 
- [ ] **Task 2** Write a function which converts (t,x,y) coordinate data into ```pandas.DataFrame```s. 

**Task 1 Description**:
The intervals data can be found [here](https://github.com/berkeley-stat222/mousestyles/tree/master/mousestyles/data/intervals). We want to create one DataFrame for each subdirectory (feature). For example, all the data from the /AS directory should be loaded into a dataframe that looks like:

strain | mouse | day | start | stop
------- | --------- | ----- | ------ | ------
0 | 1 | 1 | 289343.12 | 289392.91
0 | 1 | 1 | 321938.02 | 371938.97
... | .... | ... | ... | ...
... and so on.

I have a proposed method signature (but feel free to change this if you have a better idea):
```def load_intervals(feature):```
where feature is one of ```['AS', 'F', 'IS', 'M_AS', 'M_IS', 'W']```

The function should be added to the ```mousestyles/data/__init__.py``` file.



**Task 2 Description**:
The coordinate data can be found [here](https://github.com/berkeley-stat222/mousestyles/tree/master/mousestyles/data/txy_coords). We will have one function for each querying each mouse-day:
```def load_movement(strain, mouse, day):```
where `strain`, `mouse`, and `day` are all nonnegative integers.

The function will return a DataFrame that is formatted like this:

| t   | x  | y     | isHB | 
|---- | ---- | ---- | ---- |
2893483.11 | -10.1 | 20.1 | False |
3103930.21 | -10.3 | 20.4 | False |
... | ... | ... | ... |

where `isHB` indicates whether the point is in the home base or not (this can be found in the `C_idx_HB` directory)

**Comment by dylandaniels** [comment]
@changsiyao what I need help with is above! If you could take one of the tasks, that would be great!

**Comment by changsiyao** [comment]
@dylandaniels Sure, I can take the first task on the interval data.

**Comment by changsiyao** [comment]
@dylandaniels Can we assume we know the number of strains, mouses and days? Or do I have to detect all the files in the directory and get those info from the file name?

**Comment by dylandaniels** [comment]
@changsiyao You'll have to get that data from the file names.

**Comment by changsiyao** [comment]
@dylandaniels Sure. Also, just making sure, did you make up the start/stop numbers? cuz I'm not getting those numbers...

**Comment by dylandaniels** [comment]
@changsiyao yes, those are arbitrary.

**Comment by changsiyao** [comment]
@dylandaniels Hey, I think I got the first task done, do you want me to do task 2 as well?

**Comment by changsiyao** [comment]
Please check pull request #57 
Wrote both functions.
@dylandaniels
