### ISSUE TITLE
Revision of Overviews: Checklist

### ISSUE THREAD

**Issue by shamindras** [berkeley-stat222/mousestyles#35]
As @jarrodmillman mentioned, for the revision of **Project Overviews** i.e. #6 #8, #7, #9, #11, #12 we should have a **standard template format/ checklist** for the overviews after reviews:

- [ ] Statement of Problem
- [ ] Statement of statistical problems (including how and why it maps to the Statement of Problem)
- [ ] Exploratory Analysis
- [ ] Data Requirements Description
- [ ] Methodology/ Approach Description
- [ ] Testing Framework Outline
- [ ] Additional Remarks
- [ ] References

As I understand - the following are revisers from each team - please tick and write a comment with a link to your updated overview file after the revision:

- [ ]  #6 - @richiefeng, @HaoLyuKrystal, @gyc2432968 
- [ ]  #10 - @pttzty, @MengfeiJiang, @changsiyao 
- [ ] #8 - @peterasujan, @dylandaniels, @shamindras
- [ ] #7 -  @togawa28 @aksam-ahmad 
- [ ]  #9 - @lynnzhao @wyshi @mingyungkim 
- [ ] #11 - @z357412526 @lunadadada @cenzhuoyao 
- [ ] #12 - @jcpalumbo3, @alannaiverson, @sicihuang

**Comment by shamindras** [comment]
Hi All,

For each section of the checklist - Johnny had some excellent additional suggestions:

- [ ] **Statement of Problem**
Introduction section should include some background of the problem and one/two-sentences summarizing the objective of the subproject.
The fundamental questions section should highlight the fundamental questions we would like the subproject to address. State the main hypotheses, if any.

- [ ] **Statement of statistical problems (including how and why it maps to the Overall Problem Statement)**

- Here we need to map the underlying _Statement of Problem_ into key statistical problems e.g. classification, clustering, plotting, experimental analysis, hypothesis testing that we are trying to answer.
- Our ability to convert a general problem statement into several clear statistical problems will ensure that we communicate our ultimate goals to the Tecott Lab. This is our key strength as MA students.
- For each of statistical problems we are aiming to solve - please try and motivate it with a hypothesis or clear requirement to help address the problem.

- [ ] **Exploratory Analysis**
- The exploratory analysis section should identify questions that serve as the starting point to help refine and answer the statistical problems we are trying to solve as part of each project. The part is somewhat more open-ended relative to the key questions section.
- Write down all the data investigations, plots, models you plan to run to check your hypotheses. Note down how you think this exploratory work will help answer the statistical problems you have identified.
- The plots/ answers to these exploratory questions should help answer the and build the functions for the underlying statistical problems we are trying to solve

- [ ] **Data Requirements Description**
- The preliminary tasks section should identify what data processing/additional work is needed before we start our data analysis.
- This could involve key variable requirements e.g. AS/ IAS variables to be defined.
- You can also list additional data requirements here so that this could be flagged to the Lab. We will try and restrict our analysis to the data provided thoough.

- [ ] **Methodology/ Approach Description**

- Remember that ultimately all of these statistical problems will be addressed in the form of Python functions which we will implement in the `mousestyles` package as a group. So please also start to  think about the Python functions that you will need to create and include a short summary section here. We will change this part in the coming 2 weeks so just give it your best effort here 💯 !
- Note the timelines here for each function including exploratory work and note how the work is to be allocated across the team members e.g. John will work on statistical problem 1 and also do exploratory analysis tasks 1 and 2.

- [ ] **Testing Framework Outline**

- Have a think about the ways in which each of the statistical problems and python functions could be tested e.g. run simulations of machine learning functions with same random seed to check that results are reproducible.
- This does not have to be detailed just quick bullet points
- As @wyshi, @lynnzhao and @mingyungkim explained - testing is challenging 😄 ! 

- [ ] **Additional Remarks**

- The additional remarks section should include any comments/ideas not addressed in the previous sections, such as what additional data/explanation of the data might help the analysis.

- [ ] **References**
The reference section should include all the sources used when writing up the problem statements. Try not to cite wikipedia, as many researchers do not view it as a credible source.

**Comment by sicihuang** [comment]
@jcpalumbo3 , @alannaiverson, and I are revising #12 overview of overview. Just to clarify, should it be more about the background of this project, steps we plan to take, the 6 sub-projects etc. rather than following the checklist above? @jcyhong

**Comment by jarrodmillman** [comment]
I would try to follow the outline where it makes sense.  But you are correct that the outline appears more appropriate for the subprojects than the overview.  Use your best judgment for now.  I would try to get started as soon as you can.  It will be easier to provide feedback on what you did than to pre-specify what your revision should look like.

**Comment by shamindras** [comment]
Based on gitter comments - just want to clear confusion:
#6 (**Project 4**) - is now correctly assigned to @richiefeng, @HaoLyuKrystal who have been working on it.
#10 (**Project 5**)- is assigned to @pttzty , @changsiyao @MengfeiJiang 

@hduongtrong , @doutib @FengshiNiu - it seems that you do not have a project assigned to review.
